# Generated by Django 3.1 on 2020-08-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city_page',
        ),
        migrations.AddField(
            model_name='post',
            name='city_options',
            field=models.CharField(choices=[('SF', 'San Francisco'), ('L', 'London'), ('S', 'Seattle'), ('SY', 'Sydney')], default='SF', max_length=2, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.city'),
        ),
    ]
