# Generated by Django 3.1 on 2020-08-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city_options',
            field=models.CharField(choices=[('1', 'San Francisco'), ('2', 'Seattle'), ('3', 'London'), ('4', 'Sydney')], max_length=2, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=250, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
