# Generated by Django 3.1 on 2020-08-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200809_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_img',
            field=models.ImageField(blank=True, default='defaultpic2.png', null=True, upload_to='images/', verbose_name='Profile Image'),
        ),
    ]
