# Generated by Django 3.1 on 2020-08-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200811_1926'),
        ('main_app', '0003_auto_20200810_1459'),
        ('main_app', '0003_auto_20200810_1751'),
    ]

    operations = [
    ]
